### ISSUE TITLE
Reuse the code in this repo

### ISSUE THREAD

**Issue by wangfuzhou110** [qandeelabbassi/python-svm-sgd#1]
Hi Qandeel,

I noticed there is not a license for this repo. May I re-use your code in this repo and modify it a bit under the MIT license? I would like to compare the performance of SGD and SMO, and your code is a perfect reference. I would appreciate it very much if you could grant this to me.

Fuzhou

**Comment by danihartanto** [comment]
Jum, 15 Apr 2022 pukul 21.55 FzFox ***@***.***> menulis:

**Comment by qandeelabbassi** [comment]
@wangfuzhou110 Sure, feel free to use the code
